function loadJson(url) {
    return fetch(url)
    .then(response => {
        if (response.status == 200) {
            return response.json();
        } else {
            throw new Error(response.status);
        }
    });
}
console.log(loadJson('no-such-user.json').catch(alert)); // Error: 404

async function loadJson(url) {
    let response = await fetch(url)
        if (response.status == 200) {
             let json =  await response.json();
             return json;
        } else {
            throw new Error(response.status);
        }
}
console.log(loadJson('no-such-user.json').catch(alert)); // Error: 404


// Ask for a user name until github returns a valid user
//And get rid of the recursion in favour of a loop in demoGithubUser : with async/await that becomes easy to do.

function demoGithubUser() {
    let name = prompt("Enter a name?", "iliakan");
    return loadJson(`https://api.github.com/users/${name}`)
    .then(user => {
        alert(`Full name: ${user.name}.`);
        return user;
    })
    .catch(err => {
        if (err instanceof HttpError && err.response.status == 404) {
            alert("No such user, please reenter.");
        return demoGithubUser();
        } else {
            throw err;
        }
    });
}
demoGithubUser();

async function demoGithubUser() {
    let user;
    while(true) {
        let name = prompt("Enter a name?", "iliakan");
        try {
            user = await loadJson(`https://api.github.com/users/${name}`);
            break; // no error, exit loop
        } catch(err) {
            if (err instanceof HttpError && err.response.status == 404) {
            // loop continues after the alert
            alert("No such user, please reenter.");
        } else {
            // unknown error, rethrow
            throw err;
        }
    }
}
console.log(`Full name: ${user.name}.`);
return user;
}
demoGithubUser();


